### ISSUE TITLE
core_install.sh should check for dependent packages

### ISSUE THREAD

**Issue by dpkingston** [nwdigitalradio/n7nix#1]
This script makes some assumptions about packages that need to be installed and they are documented in the documentation, but it would be even better if it ran 'dpkg -l' or similar check to make sure they are actually installed.  It could even install them if needed.

**Comment by n7nix** [comment]
core_install.sh has a function, is_pkg_installed() that uses dpkg-query to check status of a package. All required packages are verified for installation.

**Comment by dpkingston** [comment]
You have a typo on line 8.  UPDDATE_NOW is mis-spelled.  Also, there does not appear to be any way for UPDATE_NOW to become true.

**Comment by n7nix** [comment]
Thanks. Checked in fix.
UPDATE_NOW was originally used for development.
I use it to disable apt-get update/upgrade.
Since it was undefined:

 if [ "$UPDATE_NOW" = "true" ] ; then

worked the way I wanted.

apt-get update then upgrade takes a long time & I didn't want those
long processes to be executed from the script.  My intention is that
those commands should be done outside the script so that it's easier
to see any problems. I left the apt-get update/upgrade in the script for reference.
