### ISSUE TITLE
unknown error at ./app_install.sh

### ISSUE THREAD

**Issue by z3r0l1nk** [nwdigitalradio/n7nix#2]
Hello,
Sorry if I post this in the wrong section but I don't know where to post.
After Core installation, i'm trying to run the app_install.sh and get the following error.
I'm pasting the error from rmsbuild.txt log. --> [https://pastebin.com/cvTJdKGn](url)
I'm running a Raspberry Pi Zero W.

Kind regards,
Mihai YO3ISL

**Comment by n7nix** [comment]
From your rmsbuild log your rmsgw build fails because file stdbool.h is not installed. Something in your Core installation failed. If I can take a look at the console output from ./core_install.sh & the contents of /var/log/udr_install.log I might be able to make a suggestion.
From the UDRC II product page: http://nwdigitalradio.com/product/udrc/
"Note: ARMv6 Raspberry Pis are not supported.  This includes the A/A+, Zero, Pi 1 B/B+, and Compute Module. Supported devices are the Raspberry Pi 2 B and Pi 3 B."
I would prefer you post problems to the udrc forum on groups.io
https://nw-digital-radio.groups.io/g/udrc/topics

**Comment by z3r0l1nk** [comment]
Hello again,

So this is the core_install.sh output from the console [https://pastebin.com/86NuQxG0](url).
the log file udr_install.log is empty.

**Comment by n7nix** [comment]
This is not the place for this discussion. Please become of a member of this group and post your question there.
https://nw-digital-radio.groups.io/g/udrc
